# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppChat_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(725, 440)
        Form.setMinimumSize(QtCore.QSize(725, 440))
        Form.setMaximumSize(QtCore.QSize(725, 440))
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(470, 5, 246, 401))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.pushButtonSend = QtWidgets.QPushButton(Form)
        self.pushButtonSend.setGeometry(QtCore.QRect(195, 410, 75, 23))
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.pushButtonExit = QtWidgets.QPushButton(Form)
        self.pushButtonExit.setGeometry(QtCore.QRect(640, 410, 75, 23))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(460, 415, 54, 12))
        self.label.setObjectName("label")
        self.labelUserNum = QtWidgets.QLabel(Form)
        self.labelUserNum.setGeometry(QtCore.QRect(515, 415, 54, 12))
        self.labelUserNum.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUserNum.setObjectName("labelUserNum")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(5, 5, 461, 291))
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(5, 335, 461, 71))
        self.textEdit.setObjectName("textEdit")
        self.fontComboBox = QtWidgets.QFontComboBox(Form)
        self.fontComboBox.setGeometry(QtCore.QRect(5, 305, 165, 22))
        self.fontComboBox.setObjectName("fontComboBox")
        self.sizeComboBox = QtWidgets.QComboBox(Form)
        self.sizeComboBox.setGeometry(QtCore.QRect(180, 305, 69, 22))
        self.sizeComboBox.setObjectName("sizeComboBox")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.toolButtonBold = QtWidgets.QToolButton(Form)
        self.toolButtonBold.setGeometry(QtCore.QRect(255, 300, 30, 30))
        self.toolButtonBold.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/image/bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonBold.setIcon(icon)
        self.toolButtonBold.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonBold.setCheckable(True)
        self.toolButtonBold.setAutoRaise(True)
        self.toolButtonBold.setObjectName("toolButtonBold")
        self.toolButtonItalic = QtWidgets.QToolButton(Form)
        self.toolButtonItalic.setGeometry(QtCore.QRect(285, 300, 30, 30))
        self.toolButtonItalic.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/image/italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonItalic.setIcon(icon1)
        self.toolButtonItalic.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonItalic.setCheckable(True)
        self.toolButtonItalic.setAutoRaise(True)
        self.toolButtonItalic.setObjectName("toolButtonItalic")
        self.toolButtonUnderline = QtWidgets.QToolButton(Form)
        self.toolButtonUnderline.setGeometry(QtCore.QRect(315, 300, 30, 30))
        self.toolButtonUnderline.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/image/under.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonUnderline.setIcon(icon2)
        self.toolButtonUnderline.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonUnderline.setCheckable(True)
        self.toolButtonUnderline.setAutoRaise(True)
        self.toolButtonUnderline.setObjectName("toolButtonUnderline")
        self.toolButtonColor = QtWidgets.QToolButton(Form)
        self.toolButtonColor.setGeometry(QtCore.QRect(345, 300, 30, 30))
        self.toolButtonColor.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/image/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonColor.setIcon(icon3)
        self.toolButtonColor.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonColor.setCheckable(False)
        self.toolButtonColor.setAutoRaise(True)
        self.toolButtonColor.setObjectName("toolButtonColor")
        self.toolButtonSave = QtWidgets.QToolButton(Form)
        self.toolButtonSave.setGeometry(QtCore.QRect(375, 300, 30, 30))
        self.toolButtonSave.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/image/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonSave.setIcon(icon4)
        self.toolButtonSave.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonSave.setCheckable(False)
        self.toolButtonSave.setAutoRaise(True)
        self.toolButtonSave.setObjectName("toolButtonSave")
        self.toolButtonSend = QtWidgets.QToolButton(Form)
        self.toolButtonSend.setGeometry(QtCore.QRect(405, 300, 30, 30))
        self.toolButtonSend.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/image/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonSend.setIcon(icon5)
        self.toolButtonSend.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonSend.setCheckable(False)
        self.toolButtonSend.setAutoRaise(True)
        self.toolButtonSend.setObjectName("toolButtonSend")
        self.toolButtonClear = QtWidgets.QToolButton(Form)
        self.toolButtonClear.setGeometry(QtCore.QRect(435, 300, 30, 30))
        self.toolButtonClear.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/image/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonClear.setIcon(icon6)
        self.toolButtonClear.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonClear.setCheckable(False)
        self.toolButtonClear.setAutoRaise(True)
        self.toolButtonClear.setObjectName("toolButtonClear")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButtonSend, self.tableWidget)
        Form.setTabOrder(self.tableWidget, self.pushButtonExit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButtonSend.setText(_translate("Form", "发送"))
        self.pushButtonExit.setText(_translate("Form", "退出"))
        self.label.setText(_translate("Form", "在线人数："))
        self.labelUserNum.setText(_translate("Form", "0"))
        self.sizeComboBox.setItemText(0, _translate("Form", "9"))
        self.sizeComboBox.setItemText(1, _translate("Form", "10"))
        self.sizeComboBox.setItemText(2, _translate("Form", "11"))
        self.sizeComboBox.setItemText(3, _translate("Form", "12"))
        self.sizeComboBox.setItemText(4, _translate("Form", "13"))
        self.sizeComboBox.setItemText(5, _translate("Form", "14"))
        self.sizeComboBox.setItemText(6, _translate("Form", "15"))
        self.sizeComboBox.setItemText(7, _translate("Form", "16"))
        self.sizeComboBox.setItemText(8, _translate("Form", "17"))
        self.sizeComboBox.setItemText(9, _translate("Form", "18"))
        self.sizeComboBox.setItemText(10, _translate("Form", "19"))
        self.sizeComboBox.setItemText(11, _translate("Form", "20"))
        self.sizeComboBox.setItemText(12, _translate("Form", "21"))
        self.sizeComboBox.setItemText(13, _translate("Form", "22"))
        self.toolButtonBold.setToolTip(_translate("Form", "加粗"))
        self.toolButtonBold.setText(_translate("Form", "..."))
        self.toolButtonItalic.setToolTip(_translate("Form", "倾斜"))
        self.toolButtonItalic.setText(_translate("Form", "..."))
        self.toolButtonUnderline.setToolTip(_translate("Form", "下划线"))
        self.toolButtonUnderline.setText(_translate("Form", "..."))
        self.toolButtonColor.setToolTip(_translate("Form", "字体颜色"))
        self.toolButtonColor.setText(_translate("Form", "..."))
        self.toolButtonSave.setToolTip(_translate("Form", "保存聊天记录"))
        self.toolButtonSave.setText(_translate("Form", "..."))
        self.toolButtonSend.setToolTip(_translate("Form", "发送文件"))
        self.toolButtonSend.setText(_translate("Form", "..."))
        self.toolButtonClear.setToolTip(_translate("Form", "清空聊天记录"))
        self.toolButtonClear.setText(_translate("Form", "..."))


import AppChat_qrc_rc
